// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHo8qV4GWl0kkysEaneMt44iYIUfegXKM',
    appId: '1:234049521649:web:c2b0498c62aef716052650',
    messagingSenderId: '234049521649',
    projectId: 'otp-verification-461c2',
    authDomain: 'otp-verification-461c2.firebaseapp.com',
    storageBucket: 'otp-verification-461c2.appspot.com',
    measurementId: 'G-MF80YJJRX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAATbOhpn6nUr2waCfimAz7HanpIVEj6To',
    appId: '1:234049521649:android:76f74716fa63c1dc052650',
    messagingSenderId: '234049521649',
    projectId: 'otp-verification-461c2',
    storageBucket: 'otp-verification-461c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKDPvI27ru4Z4016jN3eXs-PF_vJK6qI0',
    appId: '1:234049521649:ios:77634ad771c58f31052650',
    messagingSenderId: '234049521649',
    projectId: 'otp-verification-461c2',
    storageBucket: 'otp-verification-461c2.appspot.com',
    androidClientId: '234049521649-11q8p7nt7kbmtnt3saulh6t51m4fvs58.apps.googleusercontent.com',
    iosClientId: '234049521649-k0gu2hsrncc4lj9jm3t41jq4mcc18t9j.apps.googleusercontent.com',
    iosBundleId: 'com.example.optVerify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKDPvI27ru4Z4016jN3eXs-PF_vJK6qI0',
    appId: '1:234049521649:ios:77634ad771c58f31052650',
    messagingSenderId: '234049521649',
    projectId: 'otp-verification-461c2',
    storageBucket: 'otp-verification-461c2.appspot.com',
    androidClientId: '234049521649-11q8p7nt7kbmtnt3saulh6t51m4fvs58.apps.googleusercontent.com',
    iosClientId: '234049521649-k0gu2hsrncc4lj9jm3t41jq4mcc18t9j.apps.googleusercontent.com',
    iosBundleId: 'com.example.optVerify',
  );
}
